apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-svc-2
  namespace: test-svc-2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-svc-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-svc-2
    spec:
      containers:
      - image: harbor.idp-poc.tremolo.dev/test-svc-2/mypython:b0c2d4d
        imagePullPolicy: Always
        name: test-svc-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecret: pull-secret
      imagePullSecrets:
      - name: pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
